fix multiclient support, improve launch method to properly utilize steam runtime instead of brute-forcing dependencies

diff --git a/user-scripts/.local/bin/wu-client b/user-scripts/.local/bin/wu-client
--- a/user-scripts/.local/bin/wu-client
+++ b/user-scripts/.local/bin/wu-client
@@ -33,27 +33,18 @@ fi
 
 echo "Ensuring 'steam_appid.txt' for multiclient support"
 file_appid="$path_client/steam_appid.txt"
-appid_override='402370'
+appid_override='366220'
 if ! [[ -f "$file_appid" && "$(tr -d '\r\n' <"$file_appid")" == "$appid_override" ]]; then
       echo "steam_appid.txt missing or contains incorrect contents. Repairing" 
       echo "$appid_override" > "$file_appid"
 fi
 
-echo "Launching WurmLauncher client"
+echo "Launching WurmLauncher client with steam-run"
 cd "$path_client"
 
-# Sidestep any nasty java/jvx local conflicts by using exactly the same environment
-# that steam does, which we assume works.
-# NOTE - I'm not sure how flaky this is over time, and across different distros.
-# If this is not working for you, you can try the following:
-#
-# 1 - Launch the client from Steam frontend, and grab the steam env into a file with
-#     tr '\0' '\n' < /proc/$(pgrep -n -f WurmLauncher)/environ | sort > /tmp/env.steam.txt
-# Check that file for LD_LIBRARY_PATH in particular, and any other bits that might
-# jump out at you - you may want to diff against your shell env.
-#
-# 2 - Remove the LD_LIBRARY_PATH variable assignment before the WumLauncher execution.
-# For many users, especially those on X11 rather than Wayland, this may be just
-# fine if you have the right dependencies installed locally.
-LD_LIBRARY_PATH="$PATH_STEAMDATA/steamapps/common/SteamLinuxRuntime/var/steam-runtime/pinned_libs_32:$PATH_STEAMDATA/steamapps/common/SteamLinuxRuntime/var/steam-runtime/pinned_libs_64:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu:/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib64:$PATH_STEAMDATA/steamapps/common/SteamLinuxRuntime/var/steam-runtime/lib/i386-linux-gnu:$PATH_STEAMDATA/steamapps/common/SteamLinuxRuntime/var/steam-runtime/usr/lib/i386-linux-gnu:$PATH_STEAMDATA/steamapps/common/SteamLinuxRuntime/var/steam-runtime/lib/x86_64-linux-gnu:$PATH_STEAMDATA/steamapps/common/SteamLinuxRuntime/var/steam-runtime/usr/lib/x86_64-linux-gnu:$PATH_STEAMDATA/steamapps/common/SteamLinuxRuntime/var/steam-runtime/lib:$PATH_STEAMDATA/steamapps/common/SteamLinuxRuntime/var/steam-runtime/usr/lib:$PATH_STEAMDATA/steamapps/common/Wurm Unlimited" \
-      ./WurmLauncher
+steam_run="$PATH_STEAMDATA/ubuntu12_32/steam-runtime/run.sh"
+if [[ ! -x "$steam_run" ]]; then
+      echo "ERROR: Steam runtime wrapper not found/executable at: $steam_run" >&2
+      exit 1
+fi
+"$steam_run" ./WurmLauncher
